apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-pod-replica
  labels:
    app: my-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
        - name: myapp-container
          image: busybox
          command: [ 'sh', '-c', 'echo Hello Kubernetes! && sleep 3600' ]